# =========================
# Site
# =========================
title:            aliquis-facio
tagline:          ""
description:      ""
url:              "https://aliquis-facio.github.io"
baseurl:          ""
future:           true # 미래 날짜 포스트도 공개
paginate:         5
paginate_path:    /page:num

author:
  name:           
  url:            

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  /blog

# =========================
# Jekyll core
# =========================
markdown:         kramdown
highlighter:      rouge

# =========================
# Plugins (GitHub Pages 호환)
# =========================
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
