# Site
title:            aliquis-facio
tagline:          ""
description:      ""
url:              "https://aliquis-facio.github.io"
baseurl:          ""
future:           true # 미래 날짜 포스트도 공개
paginate:         5
paginate_path:    /page:num

author:
  name:           
  url:            

# front matter defaults
defaults:
  - scope: { path: "search" }
    values: { sitemap: false }
  - scope: { path: "tags" }
    values: { sitemap: false }
  - scope: { path: "category" }
    values: { sitemap: false }

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  /blog # 블로그를 /blog로 쓰고 싶을 때 해제

reading_time:     true
words_per_minute: 200
locale:           ko_KR

# Jekyll core
markdown:         kramdown
highlighter:      rouge
permalink:        /:title/ # 고정링크
timezone:         Asia/Seoul # 빌드 타임존 명시

kramdown:
  auto_ids:       true # 제목 자동 앵커
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false
  math_engine:    mathjax

mathjax:          true # 수식

# SCSS 빌드
sass:
  sass_dir:       _sass
  style:          compressed

# Comments / Analytics
disqus:
  shortname:      github-io-wql9y9o0sz

google:
  analytics:        G-6DVR5DH0EY

# Social
github-url:       aliquis-facio
# email:
# twitter:
# linkedin:
# instagram:

# Plugins
plugins:
  - jekyll-sitemap # sitempa.xml 자동 생성
  - jekyll-feed # RSS 피드
  - jekyll-seo-tag # SEO/OG 메타 태그 자동 생성
  - jekyll-gist
  - jekyll-paginate
  # - jekyll-mentions # @user -> github 링크 생성

# jekyll-mentions:
# base_url:         https://github.com

# Exclude (빌드 가속/깨끗한 배포)
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - gulpfile.js
  - vendor
  - CNAME
  - LICENSE
  - Rakefile
  - _unstaged/*
  # - _site
  # - src