# Site
title:            Blog
tagline:          ''
description:      ''
url:              https://aliquis-facio.github.io
baseurl:          '/blog'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      excerpt_separator:  <!--more-->
      layout: post
# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

# Jekyll
permalink:        /:year/:month/:day/:title.html
markdown:         kramdown
highlighter:      rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Social
# if you don't have any of social below, comment the line.
google:
  #plus:            #username
  analytics:        G-6DVR5DH0EY
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
# email: 
# twitter:            username
# facebook:           username
github-url:         aliquis-facio
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
#instagram:         username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:             username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-include-cache
  - jemoji

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - .gitignore

# Comments
disqus:
  shortname:      github-io-wql9y9o0sz

# Used for Hydeout's own Github page. Feel free to remove for your
# own fork.
hydeout:
  version:          
  repo:             
